version: "2"
services:
    web:
      build: .
      ports:
        - "8080:80"
        - "443:443"
      volumes:
        - ./web:/var/www/html
        #- ./configs/default.conf:/etc/nginx/conf.d/default.conf
        - ./logs/nginx:/var/log/nginx
      links:
        - php
    
      networks:
        - default

    
    php:
      build: ./php
      ports:
        - "9080:9000"
      volumes:
#        - ./web:/var/www/html
        - ./configs/php-fpm.conf:/usr/local/etc/php-fpm.conf
           
      links:
        - db
    
      networks:
        - default
    db:
      image: mysql:5.7
      ports: 
        - "3309:3306"
      environment:
        MYSQL_DATABASE: T1
        MYSQL_USER: user1
        MYSQL_PASSWORD: test1
        MYSQL_ROOT_PASSWORD: test1 
      volumes:
        - ./database:/docker-entrypoint-initdb.d
        - /root/docker_example/hello_mysql:/var/lib/mysql
      networks:
        - default

